---
replicaCount: 1
image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.5.0
  pullPolicy: Always
imagePullSecrets: []
extraEnvs: {}
container:
  port: 2000
  additionalArgs: []
resources:
  limits:
    cpu: 10m
    memory: 32Mi
  requests:
    cpu: 1m
    memory: 8Mi
service:
  type: ClusterIP
  port: 2000
nodeSelector: {}
tolerations: []
affinity: {}
podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true
priorityClassName: ""
# Custom labels for pod assignment
podLabels: {}
metrics:
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    scrapeInterval: 30s
## Specify the custom message card template for MS teams
customCardTemplate: ""
# customCardTemplate: |
#   {{ define "teams.card" }}
#   {...}
#   {{ end }}
templateFile: "/etc/template/card.tmpl"
extraConfigmapMounts: []
# extraConfigmapMounts:
#   - name: customConfigMap
#     configMap:
#       name: customConfigMapName
## Additional Volume mounts
extraVolumeMounts: []
# extraVolumeMounts:
#   - name: volume-name
#     mountPath: /etc/custom_path
connectors:
- alert: "https://ecoonline.webhook.office.com/webhookb2/3e9c2e68-c373-4c92-9ae0-32a078a599a0@1d9f9dff-d592-44ae-bc5a-878ba93ca75a/IncomingWebhook/c35d3ba7b5f042cc9c0c4ed8f6bf18f4/af056662-2529-41e3-a04e-82cf4475e0e6"
# ref: https://github.com/prometheus-msteams/prometheus-msteams#customise-messages-per-ms-teams-channel
connectorsWithCustomTemplates: []
# - request_path: /alert2
#   template_file: |
#     {{ define "teams.card" }}
#     {...}
#     {{ end }}
#   webhook_url: <webhook>
#   escape_underscores: true
# Env from existing secrets or configmaps (in same namespace), will passed through to contains 'envFrom'
envFrom: {}
# envFrom:
#   - secretRef:
#       name: my-prometheus-msteams-env-secret
#   - configMapRef:
#       name: my-prometheus-msteams-env-cm